"use client";
import { useState, useMemo, useEffect } from "react";
const BASE = 300000;
const BASE_MODS = [
  { id: "dash", name: "Dashboard Real", desc: "Ventas, stock y caja en vivo", func: ["Ventas hoy", "Stock bajo", "Caja", "Rentabilidad"] },
  { id: "inv", name: "Inventario Maestro", desc: "Tallas, colores, fotos y bodega B1", func: ["Matriz tallas", "Fotos HD", "Bodega B1", "Stock real"] },
  { id: "pos", name: "Facturación POS + DIAN", desc: "Factura electrónica en 1 clic", func: ["POS", "DIAN", "Ticket", "Cierre caja"] },
  { id: "clientes", name: "Clientes y Cartera", desc: "Crédito, abonos, recordatorios WA", func: ["Clientes", "Cartera", "Abonos", "Recordatorio WA"] },
  { id: "compras", name: "Compras Proveedores A/B/C", desc: "Unifica 3 excels con origen", func: ["Proveedor A/B/C", "Costo real", "Ganancia 40%/85%", "Importar Excel"] },
  { id: "ventas", name: "Ventas y Cotizaciones", desc: "Cotiza, vende, despacha, guía", func: ["Cotización", "Pedido B1", "Guía", "Factura"] },
  { id: "ganancia", name: "Reportes de Ganancia", desc: "40% mayor / 85% detal real", func: ["Mayor 40%", "Detal 85%", "Por proveedor", "Por ref"] },
  { id: "link", name: "Link Maestro + WA Auto", desc: "stockos.com/inv + disparo 7AM/2PM", func: ["Link filtrable", "Fotos + precios", "Disparo 7AM/2PM", "Cierra venta"] },
];
const EXTRAS = [
  { id: "fotos", name: "Fotos y Variantes", price: 30000, desc: "Fotos HD + variantes", func: ["Fotos HD", "Variantes", "Galería"] },
  { id: "barras", name: "Códigos de Barras", price: 35000, desc: "Pistola, etiquetas, scan", func: ["Scan pistola", "Etiquetas", "Código interno"] },
  { id: "sucursales", name: "Sucursales B1/B2", price: 60000, desc: "Multi-bodega", func: ["Crear B2", "Transfer B1→B2", "Stock por bodega"] },
  { id: "crm", name: "CRM Avanzado", price: 45000, desc: "Tags, campañas WA", func: ["Tags cliente", "Campañas WA", "Ranking"] },
  { id: "ecommerce", name: "E-commerce Pro", price: 70000, desc: "Link con filtros", func: ["Filtro mayor/detal", "Filtro pago", "Link personalizado"] },
  { id: "usuarios", name: "Usuarios y Roles", price: 40000, desc: "Vendedores, permisos", func: ["Vendedores", "Permisos", "Caja por usuario"] },
  { id: "api", name: "API Shopify / Woo", price: 80000, desc: "Sync stock y pedidos", func: ["Sync stock", "Sync pedidos", "Webhook"] },
];
export default function PageV16Corregido() {
  const [form, setForm] = useState({ empresa: "MAXIMA IMPORTADORES", nit: "900123456", email: "maxima@test.com", wa: "3044019899" });
  const [selected, setSelected] = useState<string[]>(["fotos", "sucursales"]);
  const [expanded, setExpanded] = useState<string>("dash");
  const [funcOn, setFuncOn] = useState<Record<string, boolean>>({});
  const [generated, setGenerated] = useState("");
  const [clienteData, setClienteData] = useState<any>(null);
  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const c = params.get("c");
    if (c) { try { setClienteData(JSON.parse(decodeURIComponent(escape(atob(c))))); } catch {} }
    const init: Record<string, boolean> = {};
    [...BASE_MODS, ...EXTRAS].forEach(m => m.func.forEach(f => init[`${m.id}::${f}`] = true));
    setFuncOn(init);
  }, []);
  const total = useMemo(() => BASE + selected.reduce((a, id) => a + (EXTRAS.find(x => x.id === id)?.price || 0), 0), [selected]);
  const handleGenerate = () => {
    if (!form.empresa || !form.email) { alert("Empresa y email"); return; }
    const payload = { n: form.empresa, empresa: form.empresa, nit: form.nit, e: form.email, email: form.email, w: form.wa, wa: form.wa, total, mods: [...BASE_MODS.map(m=>m.id), ...selected], ts: Date.now() };
    const b64 = btoa(unescape(encodeURIComponent(JSON.stringify(payload))));
    try { localStorage.setItem("stockos_last_order", JSON.stringify(payload)); const arr = JSON.parse(localStorage.getItem("stockos_orders") || "[]"); arr.push(payload); localStorage.setItem("stockos_orders", JSON.stringify(arr)); } catch {}
    setGenerated(`${typeof window !== "undefined" ? window.location.origin : ""}/admin?c=${b64}`);
  };
  const toggleFunc = (modId: string, fn: string) => setFuncOn(p => ({ ...p, [`${modId}::${fn}`]: !p[`${modId}::${fn}`] }));
  return (
    <div className="min-h-screen bg-[#F6F8FA] text-[#0A2640] antialiased">
      <nav className="sticky top-0 z-40 bg-white/90 backdrop-blur border-b border-black/[0.06]"><div className="max-w-[1120px] mx-auto px-6 h-[72px] flex justify-between items-center"><div className="flex items-center gap-3"><div className="h-9 w-9 bg-[#0A2640] rounded-xl flex items-center justify-center font-extrabold text-white">S</div><span className="font-extrabold text-[18px]">STOCKOS</span><span className="text-[10px] bg-[#0A2640]/10 px-2.5 py-1 rounded-full font-bold">V16 CORREGIDO</span></div><button onClick={() => document.getElementById("checkout")?.scrollIntoView({behavior:"smooth"})} className="h-9 px-5 bg-[#1ECB6A] text-[#0A2640] rounded-full font-bold text-[13px]">Activar $300k</button></div></nav>
      {clienteData && <div className="max-w-[1120px] mx-auto px-6 pt-6"><div className="bg-[#1ECB6A] text-[#0A2640] rounded-2xl p-5 flex justify-between"><div><div className="font-extrabold text-[11px]">CLIENTE ACTIVADO ?c= OK</div><div className="font-bold mt-1">{clienteData.n} - {clienteData.e} - ${clienteData.total?.toLocaleString("es-CO")} - {clienteData.mods?.join(", ")}</div></div><div className="bg-[#0A2640] text-white px-4 py-2 rounded-full text-[11px] font-bold">OK</div></div></div>}
      <section className="max-w-[1120px] mx-auto px-6 pt-10 pb-12 grid md:grid-cols-[1.2fr_0.8fr] gap-10 items-center"><div><div className="inline-flex bg-[#1ECB6A]/15 border border-[#1ECB6A]/20 text-[11px] font-bold px-4 py-2 rounded-full tracking-widest">V16 CORREGIDO · SIN TALLER MARCIAL · SIN DUPLICADOS</div><h1 className="mt-6 text-[42px] font-extrabold leading-[0.95] tracking-[-0.03em]">Vende 200 pares/día sin excels.<br/><span className="text-[#1ECB6A]">STOCKOS V22 base $300k.</span></h1><p className="mt-4 text-[15px] opacity-60 max-w-[520px]">Mismo diseño V16 (blanco premium #0A2640 #1ECB6A, logo, cuadros). Corregido: 8 verdes + 7 extras, cada módulo desplegable con funciones clicables ON/OFF.</p><div className="mt-7 flex gap-3"><button onClick={() => document.getElementById("checkout")?.scrollIntoView({behavior:"smooth"})} className="h-[48px] px-7 bg-[#0A2640] text-white rounded-full font-bold">Empezar $300k →</button><a href="https://wa.me/573044019899" className="h-[48px] px-7 border rounded-full font-bold flex items-center">WhatsApp</a></div></div><div className="bg-white rounded-[28px] border p-2"><div className="bg-white rounded-[24px] border p-5"><div className="text-[12px] font-bold">DEMO REAL · Máxima</div><div className="mt-3 bg-[#F6F8FA] rounded-xl p-3 text-[11px]">Inventario B1 - 1,240 pares - En vivo</div><div className="mt-3 grid grid-cols-3 gap-2 text-[11px]"><div className="bg-[#0A2640] text-white rounded-xl p-3 text-center">200<br/>pares/día</div><div className="bg-[#1ECB6A]/15 border rounded-xl p-3 text-center">$12.5M<br/>ventas</div><div className="bg-[#F6F8FA] border rounded-xl p-3 text-center">B1→B2<br/>transfer</div></div></div></div></section>
      <section id="modulos" className="max-w-[1120px] mx-auto px-6 py-12"><h2 className="text-[28px] font-extrabold">Lo que incluye tu base $300.000</h2><p className="text-[13px] opacity-60">8 verdes obligatorios + 7 extras. Sin Taller Marcial. Clic en +Funciones para ON/OFF.</p><div className="mt-6 grid md:grid-cols-2 gap-3">{BASE_MODS.map(m => { const isOpen = expanded === m.id; return (<div key={m.id} className={`bg-white border rounded-2xl overflow-hidden ${isOpen ? 'border-[#1ECB6A]' : 'border-black/5'}`}><div className="p-4 flex justify-between items-center"><div className="flex gap-3 items-center"><div className="w-8 h-8 bg-[#1ECB6A] rounded-full flex items-center justify-center font-extrabold">✓</div><div><div className="font-bold text-[14px]">{m.name}</div><div className="text-[12px] opacity-60">{m.desc}</div></div></div><button onClick={() => setExpanded(isOpen ? "" : m.id)} className="text-[11px] font-bold border rounded-full px-3 py-1.5">{isOpen ? "−" : "+"} Funciones</button></div>{isOpen && <div className="px-4 pb-4 grid grid-cols-2 gap-2">{m.func.map(fn => { const k = `${m.id}::${fn}`; const on = funcOn[k] ?? true; return <button key={fn} onClick={() => toggleFunc(m.id, fn)} className={`text-left text-[11px] font-bold p-2.5 rounded-xl border ${on ? 'bg-[#1ECB6A] border-[#1ECB6A]' : 'bg-[#F6F8FA] border-black/5 opacity-60'}`}>{fn} {on ? "✅" : "⬜"}</button>; })}</div>}</div>); })}</div><div className="mt-8 grid md:grid-cols-2 gap-3">{EXTRAS.map(ex => { const isOpen = expanded === ex.id; const sel = selected.includes(ex.id); return (<div key={ex.id} className={`bg-white border-2 rounded-2xl overflow-hidden ${sel ? 'border-[#1ECB6A] bg-[#1ECB6A]/5' : 'border-black/5'}`}><div className="p-4 flex justify-between items-center"><label className="flex gap-3 items-center cursor-pointer flex-1"><input type="checkbox" checked={sel} onChange={() => setSelected(s => s.includes(ex.id) ? s.filter(x => x !== ex.id) : [...s, ex.id])} className="w-5 h-5" /><div><div className="font-bold text-[14px]">{ex.name} <span className="text-[#1ECB6A]">+${ex.price.toLocaleString("es-CO")}</span></div><div className="text-[12px] opacity-60">{ex.desc}</div></div></label><button onClick={() => setExpanded(isOpen ? "" : ex.id)} className="text-[11px] font-bold border rounded-full px-3 py-1.5 ml-3">{isOpen ? "−" : "+"} Funciones</button></div>{isOpen && <div className="px-4 pb-4 grid grid-cols-3 gap-2 border-t pt-3">{ex.func.map(fn => { const k = `${ex.id}::${fn}`; const on = funcOn[k] ?? sel; return <button key={fn} onClick={() => toggleFunc(ex.id, fn)} className={`text-[11px] font-bold p-2 rounded-xl border text-left ${on ? 'bg-[#0A2640] text-white' : 'bg-white'}`}>{fn} {on ? "✅" : "⬜"}</button>; })}</div>}</div>); })}</div></section>
      <section id="checkout" className="max-w-[1120px] mx-auto px-6 py-12"><div className="bg-white rounded-[28px] border p-6 md:p-8"><h3 className="text-[26px] font-extrabold">Compra en línea</h3><div className="mt-4 grid gap-3"><input value={form.empresa} onChange={e => setForm({ ...form, empresa: e.target.value })} placeholder="Empresa" className="h-[52px] border rounded-xl px-4 font-bold" /><div className="grid grid-cols-2 gap-3"><input value={form.nit} onChange={e => setForm({ ...form, nit: e.target.value })} placeholder="NIT" className="h-[52px] border rounded-xl px-4" /><input value={form.wa} onChange={e => setForm({ ...form, wa: e.target.value })} placeholder="WhatsApp" className="h-[52px] border rounded-xl px-4" /></div><input value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} placeholder="Email" className="h-[52px] border rounded-xl px-4" /></div><div className="mt-6 flex justify-between items-center bg-[#0A2640] text-white rounded-2xl p-5"><div><div className="text-[11px] opacity-70">TOTAL</div><div className="text-[28px] font-extrabold">${total.toLocaleString("es-CO")}</div><div className="text-[11px] opacity-70">Base $300k + {selected.length} extras</div></div><button onClick={handleGenerate} className="h-[48px] px-6 bg-[#1ECB6A] text-[#0A2640] rounded-full font-extrabold">Crear empresa y generar link ?c=</button></div>{generated && <div className="mt-6 bg-[#1ECB6A]/10 border border-[#1ECB6A]/20 rounded-2xl p-4"><div className="font-bold text-[12px]">✅ LINK GENERADO - Mismo diseño V16 que pediste</div><div className="text-[10px] break-all bg-white border p-3 rounded-xl mt-2">{generated}</div><div className="mt-3 flex gap-2"><button onClick={() => navigator.clipboard.writeText(generated)} className="flex-1 h-10 bg-[#0A2640] text-white rounded-full font-bold text-[12px]">Copiar</button><a href={generated} className="flex-1 h-10 bg-[#1ECB6A] text-[#0A2640] rounded-full font-bold text-[12px] flex items-center justify-center">Ir a /admin →</a></div></div>}<div className="mt-8 grid grid-cols-3 gap-3"><div className="border-2 border-[#1ECB6A] rounded-2xl p-4"><div className="text-[10px] font-bold">NEQUI</div><div className="font-mono font-bold">321 598 1307</div></div><div className="border-2 border-[#0A2640] rounded-2xl p-4"><div className="text-[10px] font-bold">BANCOLOMBIA</div><div className="font-mono font-bold text-[14px]">912-510747-93</div></div><div className="border rounded-2xl p-4"><div className="text-[10px] font-bold">PAYPAL</div><div className="font-mono font-bold text-[11px] break-all">andreskstllo@gmail.com</div></div></div></div></section>
      <footer className="max-w-[1120px] mx-auto px-6 py-10 border-t flex justify-between text-[12px] opacity-60"><div>© 2026 STOCKOS · V16 Corregido · 8 verdes + 7 extras</div><div>MAXIMA IMPORTADORES</div></footer>
    </div>
  );
}
